version: "3.7"
services:
  
  team_3_API:
    build: .
    image: team_3_API_image
    container_name: team_3_API_container
    ports:
      - "8003:8003"
    links:
      - team_3_postgres_app
    env_file:
      - .env

  team_3_postgres_app:
    image: postgres
    container_name: team_3_postgres_container
    ports: 
      - "5433:5432"
    env_file:
      - .env.db.docker
    volumes:
      - team_3_postgres:/var/lib/postgresql/data

volumes:
  team_3_postgres: